token = "" # Токен пользователя

from_id = "666" # От кого будет отправляться команда
command = "start" # Команда для вызова

attachment = "" # Прикрепляющий материал
message = "" # Текст сообщения